server:
  port: 9011

spring:
  application:
    name: how-gateway-manager #指定服务名
  cloud:
    nacos:
      discovery:
        server-addr: 111.11.11.11:8848
        namespace: dev
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #路由小写

      routes:
        - id: how-gathering
          uri: lb://how-gathering
          predicates:
            - Path=/gathering/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-article
          uri: lb://how-article
          predicates:
            - Path=/article/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-base
          uri: lb://how-base
          predicates:
            - Path=/base/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-friend
          uri: lb://how-friend
          predicates:
            - Path=/friend/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-qa
          uri: lb://how-qa
          predicates:
            - Path=/qa/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-spit
          uri: lb://how-spit
          predicates:
            - Path=/spit/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-user
          uri: lb://how-user
          predicates:
            - Path=/user/** # 路径匹配
          filters:
            - StripPrefix=1
        - id: how-search #搜索
          uri: lb://how-search
          predicates:
            - Path=/search/** # 路径匹配
          filters:
            - StripPrefix=1

jwt:
  config:
    key: howblog  #注意这个key不能太短
    ttl: 360000
