server:
  port: 9009
spring:
  application:
    name: how-sms #指定服务名
  rabbitmq:
    host: 11.11.11.11
    username: guest
    password: guest

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 111.11.11.11:8848
        namespace: dev

aliyun:
  sms:
    template_code: 11
    sign_name: 11
    accessKeyId: 11
    accessKeySecret: 11