server:
  port: 9008
spring:
  application:  
    name: how-user #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.11.11.11:3306/how_user?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 11.11.11.11
    username: guest
    password: guest
  redis:
    host: 111.11.11.11
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 111.11.11.11:8848
        namespace: dev
jwt:
  config:
    key: howblog  #注意这个key不能太短
    ttl: 360000