server:
  port: 9004
spring:
  application:
    name: how-article #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.11.11.11:3306/how_article?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 111.11.11.11:8848
        namespace: dev

  redis:
    host: 111.11.11.11
  data:
    mongodb:
      host: 11.11.11.11
      database: commentdb


# 11.11.11.11  我的阿里云服务器地址