server:
  port: 9001
spring:
  application:
    name: how-base #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/how_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
