server:
  port: 9003
spring:
  application:
    name: how-qa #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/how_qa?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
#开启熔断机制
feign:
  hystrix:
    enabled: true

jwt:
  config:
    key: howblog  #注意这个key不能太短
