server:
  port: 9010
spring:
  application:
    name: how-friend #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/how_friend?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show‐sql: true

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

#开启熔断机制
feign:
  hystrix:
    enabled: true

jwt:
  config:
    key: howblog


