# PostgreSQL
version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - /usr/local/service/postgresql/data:/var/lib/postgresql/data